PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS poem_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  occasion TEXT NOT NULL,
  tone TEXT NOT NULL,
  subject TEXT NOT NULL,
  detail TEXT NOT NULL,
  budget INTEGER NOT NULL,
  total_price INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS poet_applications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  specialty TEXT NOT NULL,
  sample TEXT NOT NULL,
  rate INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS poem_bids (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  request_id INTEGER NOT NULL,
  poet_id INTEGER NOT NULL,
  amount INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (request_id) REFERENCES poem_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (poet_id) REFERENCES poet_applications(id) ON DELETE CASCADE
);
